//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.01 at 06:42:07 PM CET 
//


package net.myprojects.xsd.testscheme;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.myprojects.xsd.testscheme package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Address_QNAME = new QName("http://myprojects.net/xsd/TestScheme", "address");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.myprojects.xsd.testscheme
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressXML }
     * 
     */
    public AddressXML createAddressXML() {
        return new AddressXML();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://myprojects.net/xsd/TestScheme", name = "address")
    public JAXBElement<AddressXML> createAddress(AddressXML value) {
        return new JAXBElement<AddressXML>(_Address_QNAME, AddressXML.class, null, value);
    }

}
